server-addr="163.44.165.223"
local-dns="192.168.0.1"

addr="0.0.0.0"
protocol="tcp"
port-start = 40100
port-end = 40120
subnet = "10.1.1.1/24"
key = "ilovethebigbrother"
peertimeout = 60
mtu = 1500
logfile=""
loglevel="INFO"
