server-addr="45.76.196.181"
dns="108.61.10.10"
cipher="salsa20"
password="123456"
addr="0.0.0.0"
protocol="tcp"
server-port=40100
subnet = "10.1.1.1/24"
key = "ilovethebigbrother"
peertimeout = 60
mtu = 1500
logfile=""
loglevel="DEBUG"
