// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

/*
Package protodef is a generated protocol buffer package.

It is generated from these files:
	data.proto
	fin.proto
	handshake.proto
	header.proto
	ping.proto
	test.proto

It has these top-level messages:
	Data
	DataAck
	Fin
	FinAck
	Handshake
	HandshakeAck
	PacketHeader
	Ping
	PingAck
	TestPacket
*/
package protodef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	Header  *PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Payload []byte        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Data) GetHeader() *PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DataAck struct {
	Header *PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *DataAck) Reset()                    { *m = DataAck{} }
func (m *DataAck) String() string            { return proto.CompactTextString(m) }
func (*DataAck) ProtoMessage()               {}
func (*DataAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DataAck) GetHeader() *PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "protodef.Data")
	proto.RegisterType((*DataAck)(nil), "protodef.DataAck")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x29, 0xa9, 0x69, 0x52, 0x3c, 0x19,
	0xa9, 0x89, 0x29, 0xa9, 0x45, 0x10, 0x71, 0xa5, 0x00, 0x2e, 0x16, 0x97, 0xc4, 0x92, 0x44, 0x21,
	0x3d, 0x2e, 0x36, 0x88, 0xb8, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x98, 0x1e, 0x4c, 0x83,
	0x5e, 0x40, 0x62, 0x72, 0x76, 0x6a, 0x89, 0x07, 0x58, 0x36, 0x08, 0xaa, 0x4a, 0x48, 0x82, 0x8b,
	0xbd, 0x20, 0xb1, 0x32, 0x27, 0x3f, 0x31, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xc6,
	0x55, 0xb2, 0xe4, 0x62, 0x07, 0x99, 0xe8, 0x98, 0x9c, 0x4d, 0xaa, 0xa1, 0x49, 0x6c, 0x60, 0x69,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xfc, 0xbc, 0x8a, 0xb9, 0x00, 0x00, 0x00,
}
