// Code generated by protoc-gen-go.
// source: ping.proto
// DO NOT EDIT!

package protodef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Ping struct {
	Header *PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Ping) GetHeader() *PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type PingAck struct {
	Header *PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *PingAck) Reset()                    { *m = PingAck{} }
func (m *PingAck) String() string            { return proto.CompactTextString(m) }
func (*PingAck) ProtoMessage()               {}
func (*PingAck) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *PingAck) GetHeader() *PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*Ping)(nil), "protodef.Ping")
	proto.RegisterType((*PingAck)(nil), "protodef.PingAck")
}

func init() { proto.RegisterFile("ping.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xcc, 0x4b,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x29, 0xa9, 0x69, 0x52, 0x3c, 0x19,
	0xa9, 0x89, 0x29, 0xa9, 0x45, 0x10, 0x71, 0x25, 0x33, 0x2e, 0x96, 0x80, 0xcc, 0xbc, 0x74, 0x21,
	0x3d, 0x2e, 0x36, 0x88, 0xb8, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x98, 0x1e, 0x4c, 0x83,
	0x5e, 0x40, 0x62, 0x72, 0x76, 0x6a, 0x89, 0x07, 0x58, 0x36, 0x08, 0xaa, 0x4a, 0xc9, 0x92, 0x8b,
	0x1d, 0xa4, 0xcf, 0x31, 0x39, 0x9b, 0x54, 0xad, 0x49, 0x6c, 0x60, 0x69, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0x56, 0x59, 0xcd, 0x9f, 0x00, 0x00, 0x00,
}
